//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appleseed.Services.Search.Web {
    
    
    public partial class SearchKnockout {
        
        /// <summary>
        /// CollectionIndexKnockoutSearch1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Appleseed.Services.Search.Web.DesktopModules.CustomModules.Anant.Search.CollectionIndexKnockoutSearch CollectionIndexKnockoutSearch1;
    }
}
